version: '3'

services:
  db-postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-postgres-library-stellar-api"
    restart: always
    volumes:
      - ./database-library-stellar:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD

volumes:
  database-library-stellar:
